---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: develop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-service
      app.kubernetes.io/instance: keptn
  replicas: 1
  # recreate the deployment if anything changes (we can not do a rolling upgrade of this deployment as we use a volume)
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-service
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: develop
    spec:
      serviceAccountName: keptn-api-service
      securityContext:
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: api-service
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 5
          image: keptn/api-service:0.13.0-dev
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PREFIX_PATH
            - name: EVENTBROKER_URI
              value: http://localhost:8081/event
            - name: DATASTORE_URI
              value: mongodb-datastore:8080
            - name: CONFIGURATION_URI
              value: configuration-service:8080
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: keptn-api-token
                  key: keptn-api-token
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MAX_AUTH_REQUESTS_PER_SECOND
              value: '1.0'
            - name: MAX_AUTH_REQUESTS_BURST
              value: '2'
            - name: LOG_LEVEL
              value: debug
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              # limits is high on purpose to enable Debugging using skaffold
              # you can monitor memory usage using "kubectl -n keptn top pods"
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /data
              name: api-service-configmap-volume




        - name: distributor
          image: docker.io/keptn/distributor:0.13.0-dev
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PUBSUB_URL
              value: nats://keptn-nats-cluster
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
      volumes:
        - name: api-service-configmap-volume
          configMap:
            name: api-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/instance: keptn
