apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: keptn/remediation-service
    docker:
      dockerfile: Dockerfile
      target: production
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - deploy/service.yaml
profiles:
- name: my prof
  build:
    googleCloudBuild: {}
